import { useEffect, useMemo, useState } from "react";
import type { TmuxWindow } from "../../app/api";
import TerminalCard from "./TerminalCard";
import { loadLayout, saveLayout, type TerminalLayout, type WorkspaceLayout } from "./layout";

type Props = { windows: TmuxWindow[]; onRefresh: () => void };
export default function TerminalWall({ windows, onRefresh }: Props) {
  const [layout, setLayout] = useState<WorkspaceLayout>(loadLayout);
  const [fullscreen, setFullscreen] = useState(false);
  const known = useMemo(() => new Set(windows.map((item) => item.target)), [windows]);
  useEffect(() => { const id = setTimeout(() => saveLayout(layout), 100); return () => clearTimeout(id); }, [layout]);
  const raise = (target: string) => setLayout((current) => { const z = Math.max(0, ...current.cards.map((item) => item.z)) + 1; return { ...current, cards: current.cards.map((item) => item.target === target ? { ...item, z } : item) }; });
  const open = (target: string) => setLayout((current) => { if (current.cards.some((card) => card.target === target)) { setTimeout(() => raise(target)); return current; } const n = current.cards.length; return { ...current, cards: [...current.cards, { target, x: 28 + n * 28, y: 28 + n * 24, width: 720, height: 480, z: Math.max(0, ...current.cards.map((item) => item.z)) + 1 }] }; });
  const update = (next: TerminalLayout) => setLayout((current) => ({ ...current, cards: current.cards.map((card) => card.target === next.target ? next : card) }));
  const close = (target: string) => setLayout((current) => ({ ...current, cards: current.cards.filter((card) => card.target !== target) }));
  const arrange = (kind: "row" | "column" | "grid") => setLayout((current) => { const count = Math.max(1, current.cards.length); const columns = kind === "column" ? 1 : kind === "row" ? count : Math.ceil(Math.sqrt(count)); const rows = Math.ceil(count / columns); const width = Math.max(400, Math.floor((innerWidth - 320) / columns)); const height = Math.max(280, Math.floor((innerHeight - 100) / rows)); return { ...current, cards: current.cards.map((card, index) => ({ ...card, x: 12 + (index % columns) * width, y: 12 + Math.floor(index / columns) * height, width: width - 8, height: height - 8, z: index + 1 })) }; });
  const groups = windows.reduce<Record<string, TmuxWindow[]>>((all, item) => { (all[item.session_name] ||= []).push(item); return all; }, {});
  return <main className={`terminal-wall ${fullscreen ? "is-fullscreen" : ""}`}><aside className="wall-sidebar"><header><div><span>TMUX TERMINAL WALL</span><h1>本机终端墙</h1></div><button onClick={onRefresh}>刷新</button></header><p>直接 attach 真实 tmux window；默认镜像不影响 SSH/Tabby，点击“接管尺寸”后拖动才会改变共享 TUI 尺寸。</p><nav>{Object.entries(groups).map(([session, items]) => <section key={session}><h2>{session}</h2>{items.map((item) => <button className="wall-entry" key={item.target} onClick={() => open(item.target)}><strong>{item.target}</strong><small>{item.pane_count} pane · {item.commands.join(" / ") || "shell"}</small><small>{item.cwd_summary || "路径未知"}</small></button>)}</section>)}</nav></aside><section className="wall-main"><header className="wall-toolbar"><div><strong>{layout.cards.length} 个 window</strong><span>拖标题移动 · 拖边缩放</span></div><div><button onClick={() => arrange("row")}>横向排列</button><button onClick={() => arrange("column")}>纵向排列</button><button onClick={() => arrange("grid")}>网格排列</button><button onClick={() => setLayout({ version: 1, cards: [] })}>清空</button><button onClick={() => setFullscreen((value) => !value)}>{fullscreen ? "退出全屏" : "全屏"}</button></div></header><div className="wall-canvas">{layout.cards.length === 0 && <p className="wall-empty">从左侧选择 tmux window，开始组成终端墙。</p>}{layout.cards.map((card) => <TerminalCard key={card.target} card={card} unavailable={!known.has(card.target)} onFocus={() => raise(card.target)} onClose={() => close(card.target)} onChange={update} />)}</div></section></main>;
}
